version: '3'
services:
  discord-bot:
    build:
      dockerfile: src/Dockerfile
    container_name: discord_bot_container
    volumes:
      - .:/usr/src/app
    environment:
      - APP_SETTINGS_FILE=appSettings.local.json
    restart: always
  # mongodb:
  #   image: mongodb/mongodb-community-server:6.0-ubi8
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=user
  #     - MONGO_INITDB_ROOT_PASSWORD=pass
